# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f7e041cdfe8bd3489cda08044b76b2342eeb22a207c69586b03ed50c6f2ab7a60160f93e07578e708622229698758ac3f5195ba418e95fae2ed4d88ea6ac365

test:
  secret_key_base: 4ac33942b4b926aa53740cb5fc813f27edb57ad784c15e4ab5019937a26c44000c3932d886b50508c44fc019068f383d71fe67e624e25e54778fa5bf7ac8190e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
